export enum ROLE {
  PATIENT = 'PATIENT',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  MEDICAL_CENTER_DIRECTOR = 'MEDICAL_CENTER_DIRECTOR',
  MEDICAL_CENTER_OPERATOR = 'MEDICAL_CENTER_OPERATOR',
  INSURANCE_AGENT = 'INSURANCE_AGENT',
}

export enum STATUS {
  INACTIVE = 'INACTIVE',
  ACTIVE = 'ACTIVE',
}
